---
# Tasks file for selenium
- name: create directory
  file: "path={{ selenium_install_dir }}/selenium state=directory recurse=yes"
  tags: [configuration, selenium, selenium-create-directory]

- name: download
  get_url: "url=http://selenium-release.storage.googleapis.com/{{ selenium_version | regex_replace('\\.[0-9]+$', '') }}/selenium-server-standalone-{{ selenium_version }}.jar dest=/opt/selenium/selenium-server-standalone-{{ selenium_version }}.jar"
  tags: [configuration, selenium, selenium-download]

- name: Install browser
  apt: name={{item}}
  with_items:
    - xvfb
    - firefox
  when: ansible_os_family == 'Debian'

- name: Install browser
  yum: name={{item}}
  with_items:
    - xorg-x11-server-Xvfb
    - firefox
  when: ansible_os_family == 'RedHat'

- name: install selenium
  template: src=selenium-init-{{ ansible_os_family }}.j2 dest=/etc/init.d/selenium owner=root group=root mode=0755
  tags: [configuration, selenium, selenium-install]

#- name: run
#  service: name=selenium state=started enabled=yes
#  tags: [configuration, selenium, selenium-run]

#- name: Xvfb service on non standard port to avoid clash
#  shell: sudo Xvfb :10 -ac

#- name: export DISPLAY
#  shell: export DISPLAY=:10

# - name: run selenium
#  shell: nohup xvfb-run java -jar {{ selenium_install_dir }}/selenium/selenium-server-standalone-{{ selenium_version }}.jar -log selenium.log &
#  tags: [configuration, selenium, selenium-run]
